/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmaceutica;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.*;
/**
 *
 * @author Alunos
 */
public class RegistroRemedio extends javax.swing.JFrame {

    /**
     * Creates new form RegistroMedico
     */
    public RegistroRemedio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TextEstoqueRemedio = new javax.swing.JTextField();
        BtnRegistrarRemedio = new javax.swing.JButton();
        TextPrincipalAtivoRemedio = new javax.swing.JTextField();
        TextViaRemedio = new javax.swing.JTextField();
        TextIndicacao = new javax.swing.JTextField();
        TextIdFarmaceutico = new javax.swing.JTextField();
        TextContraIndicacaoRemedio = new javax.swing.JTextField();
        TextFormaFarmRemedio = new javax.swing.JTextField();
        TextValidadeRemedio = new javax.swing.JTextField();
        TextEfeitosColateraisRemedio = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        TextNomeRemedio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(600, 200));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        TextEstoqueRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextEstoqueRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estoque", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextEstoqueRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEstoqueRemedioActionPerformed(evt);
            }
        });

        BtnRegistrarRemedio.setBackground(new java.awt.Color(255, 36, 52));
        BtnRegistrarRemedio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        BtnRegistrarRemedio.setForeground(new java.awt.Color(255, 255, 255));
        BtnRegistrarRemedio.setText("Registrar");
        BtnRegistrarRemedio.setToolTipText("");
        BtnRegistrarRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistrarRemedioActionPerformed(evt);
            }
        });

        TextPrincipalAtivoRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextPrincipalAtivoRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Principal Ativo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextPrincipalAtivoRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPrincipalAtivoRemedioActionPerformed(evt);
            }
        });

        TextViaRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextViaRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Via de Medicação", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextViaRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextViaRemedioActionPerformed(evt);
            }
        });

        TextIndicacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextIndicacao.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indicações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextIndicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIndicacaoActionPerformed(evt);
            }
        });

        TextIdFarmaceutico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextIdFarmaceutico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Farmacéutico", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextIdFarmaceutico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdFarmaceuticoActionPerformed(evt);
            }
        });

        TextContraIndicacaoRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextContraIndicacaoRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraindicações", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextContraIndicacaoRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextContraIndicacaoRemedioActionPerformed(evt);
            }
        });

        TextFormaFarmRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextFormaFarmRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Forma Farmacêutica", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextFormaFarmRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFormaFarmRemedioActionPerformed(evt);
            }
        });

        TextValidadeRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextValidadeRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Validade", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextValidadeRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextValidadeRemedioActionPerformed(evt);
            }
        });

        TextEfeitosColateraisRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextEfeitosColateraisRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Efeitos Colaterais", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextEfeitosColateraisRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextEfeitosColateraisRemedioActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(227, 36, 52));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 102, 0), new java.awt.Color(255, 51, 0), null, null));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de Remédio");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("+");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("|");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(227, 36, 52));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jButton2.setText("<");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        TextNomeRemedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextNomeRemedio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        TextNomeRemedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextNomeRemedioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(TextValidadeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(273, 273, 273))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BtnRegistrarRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(312, 312, 312))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TextEstoqueRemedio, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(TextViaRemedio, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(TextPrincipalAtivoRemedio, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                                    .addComponent(TextNomeRemedio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 225, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TextContraIndicacaoRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextFormaFarmRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TextEfeitosColateraisRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(224, 224, 224)
                                .addComponent(TextIdFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(TextIdFarmaceutico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextIndicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNomeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextEstoqueRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextContraIndicacaoRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextPrincipalAtivoRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextEfeitosColateraisRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextViaRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFormaFarmRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TextValidadeRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(BtnRegistrarRemedio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        TextIdFarmaceutico.getAccessibleContext().setAccessibleName("ID Farmacêutico");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextEstoqueRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEstoqueRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEstoqueRemedioActionPerformed

    private void TextPrincipalAtivoRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPrincipalAtivoRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPrincipalAtivoRemedioActionPerformed

    private void TextViaRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextViaRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextViaRemedioActionPerformed

    private void TextIndicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIndicacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIndicacaoActionPerformed

    private void TextIdFarmaceuticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdFarmaceuticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdFarmaceuticoActionPerformed

    private void TextContraIndicacaoRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextContraIndicacaoRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextContraIndicacaoRemedioActionPerformed

    private void TextFormaFarmRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFormaFarmRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFormaFarmRemedioActionPerformed

    private void TextValidadeRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextValidadeRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextValidadeRemedioActionPerformed

    private void TextEfeitosColateraisRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextEfeitosColateraisRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextEfeitosColateraisRemedioActionPerformed

    private void BtnRegistrarRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistrarRemedioActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==BtnRegistrarRemedio)
{
    Remedio remedio = new Remedio();
    RemedioDAO remedioBD;
    
    remedio.setIdFarmaceutico(Integer.parseInt(TextIdFarmaceutico.getText()));
    remedio.setNome(TextNomeRemedio.getText());
    remedio.setIndicacoes(TextIndicacao.getText());
    remedio.setEstoque(Integer.parseInt(TextEstoqueRemedio.getText()));
    remedio.setContraindicacoes(TextContraIndicacaoRemedio.getText());
    remedio.setPrincipalAtivo(TextPrincipalAtivoRemedio.getText());
    remedio.setEfeitosColaterais(TextEfeitosColateraisRemedio.getText());
    remedio.setViaMedicacao(TextViaRemedio.getText());
    remedio.setFormaFarmaceutica(TextFormaFarmRemedio.getText());
    remedio.setValidade(TextValidadeRemedio.getText());
    remedioBD = new RemedioDAO();
    remedioBD.insert(remedio);
        TelaPrincipalFarmaceutico telaprincipal = new TelaPrincipalFarmaceutico();
        telaprincipal.setVisible(true);
        dispose();
    }
    }//GEN-LAST:event_BtnRegistrarRemedioActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaPrincipalFarmaceutico telaprincipal = new TelaPrincipalFarmaceutico();
        telaprincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void TextNomeRemedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextNomeRemedioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextNomeRemedioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroRemedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RegistroRemedio().setVisible(true);
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnRegistrarRemedio;
    private javax.swing.JTextField TextContraIndicacaoRemedio;
    private javax.swing.JTextField TextEfeitosColateraisRemedio;
    private javax.swing.JTextField TextEstoqueRemedio;
    private javax.swing.JTextField TextFormaFarmRemedio;
    public javax.swing.JTextField TextIdFarmaceutico;
    private javax.swing.JTextField TextIndicacao;
    private javax.swing.JTextField TextNomeRemedio;
    private javax.swing.JTextField TextPrincipalAtivoRemedio;
    private javax.swing.JTextField TextValidadeRemedio;
    private javax.swing.JTextField TextViaRemedio;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
